version: 2

models:
  - name: int_sales
    description: >
      Unified intermediate model combining Walmart and Shopify sales data. 
      Includes transactional, product, store, and temporal information.

    columns:
      - name: transaction_id
        description: Unique identifier for the transaction
        tests:
          - not_null

      - name: transaction_date
        description: The date of the transaction
        tests:
          - not_null

      - name: product_id
        description: Product ID or SKU used to identify items sold
        tests:
          - not_null

      - name: product_name
        description: Cleaned name of the product
        tests:
          - not_null

      - name: category
        description: Cleaned product category
        tests:
          - not_null

      - name: quantity
        description: Quantity of product sold in the transaction
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 0"

      - name: price
        description: Unit price of the product in the transaction
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: " >= 0"

      - name: channel
        description: Source sales channel (e.g. 'walmart', 'shopify')
        tests:
          - not_null
          - accepted_values:
              values: ['walmart', 'shopify']

      - name: store_id
        description: Store ID (only applicable for Walmart)
        
          

      - name: store_location
        description: Store location (only applicable for Walmart)
        
          

      - name: week
        description: Week of the year when the transaction occurred
        tests:
          - not_null

      - name: year
        description: Year when the transaction occurred
        tests:
          - not_null